-- Customer Profile & Revenue Drivers--

-- Q1: What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer_behavior
GROUP BY gender;

-- Q2: What is the revenue contribution of each age group?
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;

-- Q3: Do subscribed customers spend more? Compare avg spend & total revenue.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_behavior
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

-- Q4: Which age groups are most likely to subscribe?
SELECT 
    age_group,
    subscription_status,
    COUNT(DISTINCT customer_id) AS customers
FROM customer_behavior
GROUP BY age_group, subscription_status
ORDER BY age_group, customers DESC;

--Customer Loyalty & Repeat Behavior--

-- Q5: Segment customers as New, Returning, Loyal based on previous purchases.
WITH customer_type AS (
    SELECT customer_id, previous_purchases,
           CASE 
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer_behavior
)
SELECT customer_segment, COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

-- Q6: Are repeat buyers (>5 purchases) more likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q7: Which products drive repeat customers (>3 previous purchases)?
SELECT 
    item_purchased,
    COUNT(*) AS orders_from_repeat_customers,
    ROUND(SUM(purchase_amount), 2) AS revenue_from_repeat_customers
FROM customer_behavior
WHERE previous_purchases > 3
GROUP BY item_purchased
ORDER BY orders_from_repeat_customers DESC
LIMIT 10;

-- Product Performance & Customer Preferences--

-- Q8: Top 3 most purchased products within each category.
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category ORDER BY COUNT(customer_id) DESC
           ) AS item_rank
    FROM customer_behavior
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q9: Top 5 products with the highest average review rating.
SELECT item_purchased,
       ROUND(AVG(review_rating::numeric),2) AS avg_product_rating
FROM customer_behavior
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Discount Behavior & Price Sensitivity
-- Q10: Customers who used a discount AND spent above the average purchase amount.
SELECT customer_id, purchase_amount
FROM customer_behavior 
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
        SELECT AVG(purchase_amount) FROM customer_behavior
      );

-- Q11: Top 5 products with highest percentage of discounted purchases.
SELECT item_purchased,
       ROUND(
           100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
       2) AS discount_rate
FROM customer_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q12: Categories most discount-sensitive (highest discount %).
SELECT 
    category,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
    2) AS discount_share_pct,
    COUNT(*) AS total_orders
FROM customer_behavior
GROUP BY category
ORDER BY discount_share_pct DESC;

--Shipping Choice & Customer Experience

-- Q13: Compare average purchase amounts for Standard vs Express shipping.
SELECT shipping_type, 
       ROUND(AVG(purchase_amount),2) AS avg_purchase_amount
FROM customer_behavior
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Q14: Does Express shipping improve customer satisfaction (avg review rating)?
SELECT 
    shipping_type,
    ROUND(AVG(review_rating::numeric), 2) AS avg_rating,
    COUNT(*) AS total_orders
FROM customer_behavior
GROUP BY shipping_type
ORDER BY avg_rating DESC;

-- Seasonality of Demand
-- Q15: Seasonal demand – revenue by season and category.
SELECT 
    season,
    category,
    COUNT(*) AS total_orders,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_behavior
GROUP BY season, category
ORDER BY season, total_revenue DESC;


